### ISSUE TITLE
No osx package

### ISSUE THREAD

**Issue by AbdealiLoKo** [conda-forge/hdfs3-feedstock#10]
Looks like this library does not compile for OSX in https://anaconda.org/conda-forge/hdfs3
Any reason for this ? I'd like to use it on my mac

**Comment by martindurant** [comment]
The compilation required for libhdfs3 is not the same for osx as it is for linux. It is not that different, however, so it should not be too much effort for someone to put it in place (and for the dependencies too). Such a contribution would be greatly appreciated!

**Comment by AbdealiLoKo** [comment]
@martindurant  - can you check https://github.com/conda-forge/libhdfs3-feedstock/pull/16 and https://github.com/conda-forge/hdfs3-feedstock/pull/12 please
