### ISSUE TITLE
Can not find the shared library: libhdfs3.so

### ISSUE THREAD

**Issue by iniyanp** [conda-forge/hdfs3-feedstock#14]
Hi,

I am trying to install hdfs3 using pip in centos. But when I try to use `HDFileSystem()`, it is throwing `Can not find the shared library: libhdfs3.so` ERROR.

Steps I followed:

```
curl -L "https://bintray.com/wangzw/rpm/rpm" -o /etc/yum.repos.d/bintray-wangzw-rpm.repo \
    && yum makecache \
    && yum install -y libhdfs3 libhdfs3-devel \
    && pip install hdfs3
```

I have tried installing via conda. It works. But unfortunately we can't use conda in our environment for some reasons.

Could anyone help me? Thanks

**Comment by martindurant** [comment]
Did `yum install -y libhdfs3 libhdfs3-devel` succeed? I didn't even know about RPMs for libhdfs3.

**Comment by martindurant** [comment]
I recommend using conda only, that is the tested path.
Alternatively, you may wish to try pyarrow's hdfs implementation, sicne this release is old and not well maintained by now.

**Comment by iniyanp** [comment]
@martindurant yes it succeeded. yeah we are trying pyarrow as well. but they don't have release version which supports HA. They have that support merged into master. But no release as of today.

**Comment by martindurant** [comment]
Can you consider conda for installation?

**Comment by martindurant** [comment]
You can try running the first few lines of the lib module yourself to see in what manner importing the .so is failing, if you want to try to debug this yourself. It may be incompatibility with the specific version in the RPM.

**Comment by iniyanp** [comment]
@martindurant I can consider Conda for hdfs3 installation. I hope we can use both conda and pip. (Not sure. I have to give a try) . we had lot of dependency on pip libraries. Don't want to install those libraries using conda.

**Comment by martindurant** [comment]
Using conda does not prevent you from using pip.

**Comment by iniyanp** [comment]
Thanks @martindurant for your help . So I install all the existing libraries with pip. and install hdfs3 with conda.
